export * from "./section";
export * from "./card-movie";
export * from "./carousel";
export * from "./coating";
export * from "./wrapper-card";
export * from "./pagination";
export * from "./input";
export * from "./button";
export * from "./login-register";
